config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"

  get	     "/items",	            to: "items#index",   as: :items
  get	     "/items/new",	        to: "items#new",     as: :items_new
  post	   "/items",	            to: "items#create",  as: :items_create
  get	     "/items/:id",	        to: "items#show",    as: :items_show
  get	     "/items/:id/edit",	    to: "items#edit",    as: :items_edit
  patch  	 "/items/:id",	        to: "items#update",  as: :items_update
  delete	 "/items/:id",	        to: "items#destroy", as: :items_destroy

end

app/models/item.rb
class Item < ActiveRecord::Base


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
     @item = Item.new
  end

  def create
    @item = Item.new(find_params)
    if @item.save
      redirect_to items_path(@item)
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(find_params)
      redirect_to items_show_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def find_params
    params.require(:item).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= form_for @item, url: {action: "update"} do |item| %>
  <div class="form-group">
    <label>Name</label>
    <%= item.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Description</label>
    <%= item.text_area :description, class: "form-control" %>
  </div>
  <%= item.submit "Save", class: "btn btn-default" %>
<% end %>

app/views/items/index.html.erb
<h2>Tasks</h2>

<% @items.each do |item| %>
  <%= link_to "Edit #{item.name}", items_edit_path(item), class:"btn btn-default" %>
  <%= item.name %> *
  <%= item.description %>
  <%= link_to "Mark #{item.name} as Complete", items_destroy_path(item), class: "btn btn-danger", onclick: "myFunction(event)"%><br>
<% end %>

app/views/items/new.html.erb
<h2><%= @item.name%></h2>

<%= form_for @item, url: {action: "create"} do |item| %>
  <div class="form-group">
    <label>Name</label>
    <%= item.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Description</label>
    <%= item.text_area :description, class: "form-control" %>
  </div>
  <%= item.submit "Save", class: "btn btn-default" %>
<% end %>

app/views/items/show.html.erb
<p>Name: <%= @item.name %>
<p>Description: <%= @item.description %>
<p>

<%= link_to "Edit #{@item.name}", items_edit_path(@item), class:"btn btn-default" %>
<%= link_to "DELETE", items_destroy_path(@item), class: "btn btn-danger", onclick: "myFunction(event)"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <h1>To Do List</h1>
    <br>
    <%= link_to "Add New Task", items_new_path %>
    <%= link_to "View All Tasks", items_path %>
    <p>

    <%= yield %>

  </div>
</body>
</html>